githubActions and backend statefile on hashicorp 6

diff --git a/.github/workflows/terraformAction.yml b/.github/workflows/terraformAction.yml
--- a/.github/workflows/terraformAction.yml
+++ b/.github/workflows/terraformAction.yml
@@ -74,7 +74,14 @@ jobs:
       # Step 6: Output the Droplet IP
       - name: Get Droplet IP
         id: droplet_ip
-        run: echo "DROPLET_IP=$(terraform output -raw droplet_ip)" >> $GITHUB_ENV
+        run: |
+         DROPLET_IP=$(terraform output -raw droplet_ip || echo "0.0.0.0")
+         if [ "$DROPLET_IP" == "0.0.0.0" ]; then
+          echo "Error: Unable to retrieve Droplet IP."
+          exit 1
+         fi
+          echo "DROPLET_IP=${DROPLET_IP}" >> $GITHUB_ENV
+    
 
       # Optional Step: Remove the secrets.tfvars file
       - name: Cleanup secrets.tfvars
